version: '2.3'
services:
  openemis-mailhog:
    image: phpdockerio/mailhog:latest
    container_name: openemis-mailhog-2
    ports:
      - "8125:8025"
  openemis-mysql-3:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: openemis
      MYSQL_USER: openuser
      MYSQL_PASSWORD: openpass
    # command: mysqld --verbose --help # 'mysqld --sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION --max_allowed_packet=32505856'
    ports:
      - "8106:3306"
    restart: always
  openemis-nginx:
    build: ./nginx
    container_name: openemis-nginx-2
    ports:
    - "8180:80"
    links:
      - openemis-php-fpm
    restart: always
  openemis-php-fpm:
    build: ./php-fpm
    container_name: openemis-php-fpm-2
    links:
      - openemis-mailhog
      - openemis-mysql-3
